#!/bin/bash

source utils.sh

#-----------------------------------------------------
# Commandline arguments
#----------------------------------------------------

while [ "$1" != "" ]; do
    case $1 in
        -s |--search )     shift
							page=0
							sstring="$@"
							sstring=`echo $sstring |awk '{gsub(/ /,"%20");print}'`
							if_main_all
							;;
		-h |--help )		usage #shows arguments
                            exit
							;;
		-a |--about )		about
							exit
							;;
        -v |--version )     version
							;;
		* )                 error_exit
	esac
	shift
done


